image: atlassian/default-image:3

pipelines:
    pull-requests:
        "**":
            - step:
                name: Install Node Dependencies
                caches:
                    - node-modules
                    - npm
                    - nvm
                script:
                    - nvm install v17.2.0
                    - npm i -g npm@8
                    - npm ci
            - step:
                name: Lua Check
                script:
                    - apt-get update
                    - apt-get -y install lua5.1
                    - apt-get -y install luarocks
                    - luarocks install luacheck
                    - luacheck .
    tags:
        "*":
            - step:
                name: Install Node Dependencies
                caches:
                    - node-modules
                    - npm
                    - nvm
                script:
                    - nvm install v17.2.0
                    - npm i -g npm@8
                    - npm ci
            - step:
                name: Lua Check
                script:
                    - apt-get update
                    - apt-get -y install lua5.1
                    - apt-get -y install luarocks
                    - luarocks install luacheck
                    - luacheck .
            - step:
                name: Deploy to ContentDB
                caches:
                    - node-modules
                    - npm
                    - nvm
                script:
                    - nvm use v17.2.0
                    - npm run push:ci -- --token=$CONTENT_DB_EVERNESS_TOKEN --title=$BITBUCKET_TAG
definitions:
    caches:
        node-modules:
            key:
                files:
                    - package-lock.json
            path: ./node_modules
        npm:
            key:
                files:
                    - package.json
            path: ~/.npm
        nvm:
            key:
                files:
                    - .nvmrc
            path: ~/.nvm
